[keyboard]
name = "corne-rs"
product_name = "corne-rs"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "rmk"
chip = "nrf52840"

[layout]
# WARNING: Currently row2col/col2row is set in RMK's feature gate, configs here do nothing actually
# row2col = true
rows = 4
cols = 12
layers = 8
keymap = [
    [
        [
            "Tab",
            "Quote",
            "Comma",
            "Dot",
            "P",
            "Y",
            "F",
            "G",
            "C",
            "R",
            "L",
            "Backspace",
        ],
        [
            "LCtrl",
            "A",
            "O",
            "E",
            "U",
            "I",
            "D",
            "H",
            "T",
            "N",
            "S",
            "Enter",
        ],
        [
            "LShift",
            "Semicolon",
            "Q",
            "J",
            "K",
            "X",
            "B",
            "M",
            "W",
            "V",
            "Z",
            "RShift",
        ],
        [
            "__",
            "__",
            "__",
            "LGui",
            "TT(5)",
            "Enter",
            "Space",
            "MO(6)",
            "RAlt",
            "__",
            "__",
            "__",
        ],
    ],
    [
        [
            "Kc1",
            "A",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
    ],
    [
        [
            "Kc2",
            "B",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
    ],
    [
        [
            "Kc3",
            "C",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
    ],
    [
        [
            "Kc4",
            "D",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
    ],
    [
        [
            "Kc5",
            "E",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
    ],
    [
        [
            "Kc6",
            "F",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
    ],
    [
        [
            "Kc7",
            "G",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
        [
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
            "__",
        ],
    ],
]

[ble]
enabled = true

[behavior]
tap_hold = { enable_hrm = true }

[split]
connection = "ble"

[split.central]
rows = 4
cols = 6
row_offset = 0
col_offset = 0
ble_addr = [0x18, 0xe2, 0x21, 0x80, 0xc0, 0xc7]
[split.central.matrix]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
output_pins = ["P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]

[[split.peripheral]]
rows = 4
cols = 6
row_offset = 0
col_offset = 6
ble_addr = [0x7e, 0xfe, 0x73, 0x9e, 0x66, 0xe3]
[split.peripheral.matrix]
input_pins = ["P0_22", "P0_24", "P1_00", "P0_11"]
output_pins = ["P1_11", "P1_13", "P1_15", "P0_02", "P0_29", "P0_31"]

# [[split.peripheral]]
# rows = 2
# cols = 1
# row_offset = 2
# col_offset = 2
# serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
# input_pins = ["PIN_9", "PIN_11"]
# output_pins = ["PIN_10"]
